routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/book', 'HomeController@book');
Route::get('item/detail/{id}', 'HomeController@itemDetail')->name('item.detail');
Route::get('item/categories/{id}/{name}', 'HomeController@categories')->name('item.categories');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function (){

    Route::group(['prefix' => 'auth', 'as' => 'admin.'], function(){
       Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
       Route::post('login', 'Auth\LoginController@login');
       Route::post('logout', 'Auth\LoginController@logout')->name('logout');

       Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('forgot');
       Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
       Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('reset');
       Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');
    });

    # Kalau sudah login
    Route::group(['middleware' => 'admin'], function (){
        Route::get('home', 'MainController@index')->name('home');
        Route::resource('user', 'UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'admin.profile.edit', 'uses' => 'ProfileController@edit']);
        Route::put('profile', ['as' => 'admin.profile.update', 'uses' => 'ProfileController@update']);
        Route::put('profile/password', ['as' => 'admin.profile.password', 'uses' => 'ProfileController@password']);

        Route::group(['namespace' => 'Item'], function (){
            Route::group(['prefix' => 'listing'], function(){
                Route::get('form', 'ItemController@showAddForm')->name('admin.listing.form');
                Route::post('form', 'ItemController@addForm');
                Route::get('edit/{id}', 'ItemController@editItem')->name('admin.listing.edit');
                Route::post('update', 'ItemController@updateItem')->name('admin.listing.update');
                Route::get('delete/{id}', 'ItemController@deleteItem')->name('admin.listing.delete');
                Route::post('photos/{id?}/delete', 'ItemController@stockPhotoDelete')->name('admin.listing.photo.delete');
                Route::post('get_city}', 'ItemController@getCity')->name('admin.listing.getCity');
            });
            Route::group(['prefix' => 'item'], function(){
                Route::get('list',  'ItemController@index')->name('admin.item');
                Route::get('activate/{id}',  'ItemController@activateItem')->name('admin.item.activate');
                Route::get('deactivate/{id}',  'ItemController@deactivateItem')->name('admin.item.deactivate');
            });
        });
        Route::group(['prefix' => 'transaction'], function(){
            Route::get('list',  'TransactionController@index')->name('admin.transaction');            
            Route::get('detail/{id}',  'TransactionController@detail')->name('admin.transaction.detail');            
            Route::get('set_payed/{id}',  'TransactionController@setPayed')->name('admin.transaction.setPayed');
            Route::get('set_notpayed/{id}',  'TransactionController@setNotPayed')->name('admin.transaction.setNotPayed');
            Route::get('set_canceled/{id}',  'TransactionController@setCanceled')->name('admin.transaction.setCanceled');            
        });

    });

});


// User Registered
Route::group(['prefix' => 'user', 'namespace' => 'User'], function (){
    Route::group(['prefix' => 'auth', 'as' => 'user.'], function(){
      Auth::routes();
    });

    // Route::get('password/forgot', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('send.password.email');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('user.password.request');
    // Route::get('activate/{code?}', 'MainController@activateAccount')->name('user.account.activate');
    // Route::post('activate/{code?}', 'MainController@activateAccountPost')->name('user.account.activate.update');
    // Route::get('message/list', 'MainController@messageList')->name('user.message.list');

    // Loged In
    Route::group(['middleware' => 'user'], function (){
        // Route::resource('user', 'UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'user.profile.edit', 'uses' => 'ProfileController@edit']);
        Route::put('profile', ['as' => 'user.profile.update', 'uses' => 'ProfileController@update']);
        Route::put('profile/password', ['as' => 'user.profile.password', 'uses' => 'ProfileController@password']);
        Route::get('home', 'MainController@index')->name('user.home');
        Route::get('home/{id?}', 'MainController@index')->name('user.home.read');
        Route::post('home', 'MainController@updateProfile')->name('user.updateprofile');

        // Items Route
            Route::group(['namespace' => 'Item'], function (){
                Route::group(['prefix' => 'listing'], function(){
                    Route::get('form', 'ItemController@showAddForm')->name('user.listing.form');
                    Route::post('form', 'ItemController@addForm');
                    Route::get('edit/{id}', 'ItemController@editItem')->name('user.listing.edit');
                    Route::post('update', 'ItemController@updateItem')->name('user.listing.update');
                    Route::get('delete/{id}', 'ItemController@deleteItem')->name('user.listing.delete');
                    Route::post('photos/{id?}/delete', 'ItemController@stockPhotoDelete')->name('user.listing.photo.delete');
                });
                Route::group(['prefix' => 'item'], function(){
                    Route::get('list',  'ItemController@index')->name('user.item');
                });
            });
        
        // Sales Route
        Route::group(['prefix' => 'sales'], function(){
                Route::get('list', 'SalesController@index')->name('user.transaction.sales');                
                Route::get('detail{id}', 'SalesController@detail')->name('user.transaction.sales.detail');                
            });            
        // Order Route
        Route::group(['prefix' => 'order'], function(){
                Route::get('list',  'OrderController@index')->name('user.transaction.order');    
                Route::get('detail{id}',  'OrderController@detail')->name('user.transaction.order.detail');    
            });                                 

    });

    // Cart
    Route::group(['prefix' => 'cart'], function () {
        Route::get('list','CartController@index')->name('user.cart.list');
        Route::post('add','CartController@add')->name('user.cart.add');
        Route::get('delete/{id}','CartController@delete')->name('user.cart.delete');
        Route::get('inc_quantity/{id}','CartController@incQuantity')->name('user.cart.inc');
        Route::get('dec_quantity/{id}','CartController@decQuantity')->name('user.cart.dec');
    });

    // Checkout
    Route::group(['prefix' => 'checkout'], function () {
        // Route::get('/',  'CheckoutController@index')->name('user.checkout.list');
        Route::get('add/{id}',  'CheckoutController@index')->name('user.checkout.add');
        Route::post('get_city',  'CheckoutController@getCity')->name('user.checkout.add.getCity');
        Route::post('get_ongkir',  'CheckoutController@getOngkir')->name('user.checkout.add.getOngkir');
        Route::post('checkouted',  'CheckoutController@checkouted')->name('user.checkout.checkouted');
        Route::post('checkout/payment',  'CheckoutController@payment')->name('user.checkout.payment');
        Route::get('checkout/print_invoice/{id}',  'CheckoutController@invoice')->name('user.checkout.invoice');
    });   


});

app/Models/TransactionDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TransactionDetail extends Model
{
    public function transaction()
    {
        return $this->belongsTo(Transaction::class, 'id_transaction', 'id');
    }    

    public function item()
    {
        return $this->hasOne(Item::class, 'id', 'id_item');
    }

    public function user()
    {
        return $this->hasOne(User::class, "id", "id_owner");
    }
    public function getAddressCountryAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $address=$value['country'];            
        }        
        return $address;
    }
    public function getAddressCityAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $id_city=$value['city'];            
        }
        $city=City::findOrFail($id_city);
        return $city->city_name;
    }
    public function getAddressProvinceAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $id_province=$value['province'];            
        }
        $province=Province::findOrFail($id_province);
        return $province->province;
    }
    public function getAddressPostalAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $postal_code=$value['postal_code'];            
        }       
        return $postal_code;
    }
    public function getAddressPhoneAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $number_phone=$value['number_phone'];            
        }       
        return $number_phone;
    }
    public function getAddressDetailAttribute(){
        $address=json_decode(json_decode(json_encode($this->send_address),true),true);
        foreach ($address as $key => $value) {
            $detail=$value['detail'];            
        }       
        return $detail;
    }
    public function getPayedLinkAttribute(){
        return route('admin.transaction.setPayed',["id"=>$this->id]);
    }
    public function getNotpayedLinkAttribute(){
        return route('admin.transaction.setNotPayed',["id"=>$this->id]);
    }
    public function getCanceledLinkAttribute(){
        return route('admin.transaction.setCanceled',["id"=>$this->id]);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('admin.users.index', ['users' => $model->paginate(15)]);
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->create($request->merge(['password' => Hash::make($request->get('password'))])->all());

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }
}

app/Http/Controllers/User/CartController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Cart;
use Alert;
use App\Models\Item;
class CartController extends Controller{

    public function index(){
        if (!isset(Auth::user()->id)) {
            Alert::Error('Login First To Add','Error');
            return redirect('user/auth/login');
        }
        \Cart::session(Auth::user()->id);           
        return view('user.cart.index');
    }

    public function add(Request $request){
        $item=Item::findOrFail($request->id);                      
        if (!isset(Auth::user()->id)) {
            Alert::Error('Login First To Add','Error');
            return redirect('user/auth/login');
        }
        if ($item['id_user'] == Auth::user()->id) {
            Alert::error("You can't buy your item!!","Error");
            return redirect()->back();
        }
        \Cart::session(Auth::user()->id);        
        Cart::add(
            array(
                'id'=>$item->id,                
                'name'=>$item->name,
                'price'=>$item->price,
                'quantity'=>1,
            )
        );

        Alert::success('Item added to cart!', 'success');

        return redirect()->back();
    }

    public function delete($id){
        \Cart::session(Auth::user()->id);              
        Cart::remove($id);
        Alert::success('Success Delete Cart !!!','Success');
        return redirect()->back();
    }

    public function incQuantity($id){
        $item=Item::findOrFail($id);                      
        if (!isset(Auth::user()->id)) {
            Alert::Error('Login First To Add','Error');
            return redirect('user/auth/login');
        }
        if ($item['id_user'] == Auth::user()->id) {
            Alert::error("You can't buy your item!!","Error");
            return redirect()->back();
        }
        \Cart::session(Auth::user()->id);        
        Cart::update($id,
            array(                
                'quantity'=>+1,
            )
        );        
        return redirect()->back();
    }

    public function decQuantity($id){       
        $item=Item::findOrFail($id);          
        if (!isset(Auth::user()->id)) {
            Alert::Error('Login First To Add','Error');
            return redirect('user/auth/login');
        }
        if ($item['id_user'] == Auth::user()->id) {
            Alert::error("You can't buy your item!!","Error");
            return redirect()->back();
        }
        \Cart::session(Auth::user()->id);        
        Cart::update($id,
            array(                
                'quantity'=>-1,
            )
        );        
        return redirect()->back();
    }

}

app/Http/Controllers/User/MainController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Item;
use Illuminate\Support\Facades\Auth;

class MainController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        
        return view('user.dashboard.dashboard');
    }
}

app/Http/Controllers/User/SalesController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Item;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SalesController extends Controller
{
    public function index(){
        $data['data']=Transaction::whereHas('transactionDetail',function($query){
        $query->where('id_owner',Auth::user()->id);
        }        
        )->where('id_buyer','!=',Auth::user()->id)->groupBy('code')->orderBy('created_at','desc')->paginate(9); 
        return view('user.dashboard.transaction.sales.index',$data);
    }
    public function detail($id){
        $data['data']=TransactionDetail::where('id_transaction',$id)->first();
        return view('user.dashboard.transaction.detail',$data);
    }
}

resources/views/user/checkout/invoice.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Invoice</title>
	<link href="{{asset('user')}}/css/bootstrap.min.css" rel="stylesheet">
	<script src="{{asset('user')}}/js/bootstrap.min.js"></script>
	<script src="{{asset('user')}}/js/jquery.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body p-0">
						<div class="row p-5">
							<div class="col-md-6">
								<img style="max-width:220px;" src="{{asset('icon/new/icon.png')}}">
							</div>
	
							<div class="col-md-6 text-right">
								<p class="font-weight-bold mb-1">Invoice</p>
								<p class="text-muted">{{date('Y-m-d')}}</p>
							</div>
						</div>
	
						<hr class="my-5">
	
						<div class="row pb-5 p-5">
							<div class="col-md-6">
								<p class="font-weight-bold mb-4">Client Information</p>
							<p class="mb-1">{{$data->transaction->buyer->name}}</p>
								{{-- <p>Acme Inc</p> --}}
							<p class="mb-1">{{$data->address_province}}, {{$data->address_country}}</p>
							<p class="mb-1">{{$data->address_postal}}</p>
							</div>
	
							{{-- <div class="col-md-6 text-right">
								<p class="font-weight-bold mb-4">Payment Details</p>
								<p class="mb-1"><span class="text-muted">VAT: </span> 1425782</p>
								<p class="mb-1"><span class="text-muted">VAT ID: </span> 10253642</p>
								<p class="mb-1"><span class="text-muted">Payment Type: </span> Root</p>
								<p class="mb-1"><span class="text-muted">Name: </span> John Doe</p>
							</div> --}}
						</div>
	
						<div class="row p-5">
							<div class="col-md-12">
								<table class="table">
									<thead>
										<tr>
											<th class="border-0 text-uppercase small font-weight-bold">ID</th>
											<th class="border-0 text-uppercase small font-weight-bold">Item</th>
											<th class="border-0 text-uppercase small font-weight-bold">Description</th>
											<th class="border-0 text-uppercase small font-weight-bold">Quantity</th>
											<th class="border-0 text-uppercase small font-weight-bold">Unit Cost</th>
											<th class="border-0 text-uppercase small font-weight-bold">Total</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>{{$data->item->id}}</td>
											<td>{{$data->item->name}}</td>
										<td>{{$data->address_detail}}</td>
										<td>{{$data->quantity}}</td>
											<td>Rp. {{number_format($data->price,2,".",",")}}</td>
											<td>Rp. {{$data->transaction->total}}</td>
										</tr>										
									</tbody>
								</table>
							</div>
						</div>
	
						<div class="d-flex flex-row-reverse bg-dark text-white p-4">
							<div class="py-3 px-5 text-right">
								<div class="mb-2">Grand Total</div>
							<div class="h2 font-weight-light">Rp. {{number_format($data->transaction->total)}}</div>
							</div>
	
							<div class="py-3 px-5 text-right">
								{{-- <div class="mb-2">Discount</div>
								<div class="h2 font-weight-light">10%</div> --}}
							</div>
	
							<div class="py-3 px-5 text-right">
								{{-- <div class="mb-2">Sub - Total amount</div>
								<div class="h2 font-weight-light">$32,432</div> --}}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		
	
	</div>
		
</body>
<script>
$(document).ready(function () {
	window.print();
});
</script>
</html>

resources/views/user/checkout/payment.blade.php
@extends('user.layouts.app')
@section('content')
<section style="margin-bottom:20px;">
    <div class="container">
        <div class="row justify-content-center">
        {{-- @include('user.layouts.sidebar') --}}        
            <div class="col-sm-12 padding-right text-center">
                <h3>Transfer Your Money To This Rekenening To Continue:</h3><br>
                @foreach ($rekening as $item)
                    <h3 style="letter-spacing:10px;">
                        {{$item->rekening}}
                    </h3><br>
                    @endforeach<br><br>
                <a href="{{route('user.checkout.invoice',["id"=>$id])}}" target="_blank">
                    <button style="" type="submit" onclick="" class="btn btn-fefault cart">
                            <i class="fa fa-print"></i>
                            Print Invoice
                        </button>	
                    </a>
                        <br><br>
            </div>
        </div>
    </div>
</section>
@endsection